# Site + Plant Parameters
site:
  depth: 40 # 34 COE
  distance: 120
  distance_to_landfall: 50
  mean_windspeed: 9
plant:
  layout: grid
  num_turbines: 50 # 40 COE
  row_spacing: 7
  substation_distance: 1
  turbine_spacing: 7
landfall:
  interconnection_distance: 3
  trench_length: 2
turbine: 15MW_generic
# Vessels
support_vessel: example_support_vessel
towing_vessel: example_towing_vessel
towing_vessel_groups:
    towing_vessels: 3
    station_keeping_vessels: 2
array_cable_install_vessel: example_cable_lay_vessel
export_cable_install_vessel: example_cable_lay_vessel
export_cable_bury_vessel: example_cable_lay_vessel
oss_install_vessel: example_heavy_lift_vessel
spi_vessel: example_scour_protection_vessel
ahts_vessel: example_ahts_vessel
wtiv: example_wtiv
# Substructure
substructure: 
    unit_cost: 10000000
    takt_time: 0
port:
    sub_assembly_lines: 1  
    turbine_assembly_cranes: 1 
    sub_storage: 1   
    assembly_storage: 1   
# Module Specific
scour_protection_design: 
  cost_per_tonne: 40
  scaling_factor: 1.5
  scour_protection_diameter: 60   
  scour_protection_depth: 0.8  
OffshoreSubstationInstallation:
  feeder: example_heavy_feeder
  num_feeders: 1
array_system_design:
  cables:
  - XLPE_185mm_66kV
  - XLPE_630mm_66kV
export_system_design:
  cables: XLPE_1000mm_220kV
  percent_added_length: 5.0
# Configured Phases
design_phases:
- MonopileDesign
- ArraySystemDesign
- ExportSystemDesign
- OffshoreSubstationDesign
- ScourProtectionDesign
install_phases:
  ArrayCableInstallation: 0
  ExportCableInstallation: 2000
  MonopileInstallation: 0
  TurbineInstallation: 0
  OffshoreSubstationInstallation: 0
  ScourProtectionInstallation: 0
  
# Project Inputs
project_parameters:
  turbine_capex: 1700
